using Bulldozer.Compilers;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace Bulldozer.Tests
{
	[TestClass]
	public class Tests
	{
		[TestMethod]
		public void Coffee()
		{
			CompileResult result = CoffeeScriptCompiler.Compile("alert 'asdf'");
			Assert.AreEqual("// Generated by CoffeeScript 1.7.1\n(function() {\n  alert('asdf');\n\n}).call(this);", result.Content);
		}

		[TestMethod]
		public void CoffeeError()
		{
			CompileResult result = CoffeeScriptCompiler.Compile("asdf(");
			Assert.AreEqual("Error on line 0 on column 5:\nmissing )", result.Content);
		}

		[TestMethod]
		public void Less()
		{
			CompileResult result = LessCompiler.Compile("@x: #000; a { color: @x; }");
			Assert.AreEqual("a {\n  color: #000000;\n}", result.Content);
		}

		[TestMethod]
		public void LessError()
		{
			CompileResult result = LessCompiler.Compile("@x: #000; a { color: @y; }");
			Assert.AreEqual("Error on line 1:\nvariable @y is undefined", result.Content);
		}
	}
}